image: ruby:3.0.1

services:
   - mysql:5.7.19

variables:
   RAILS_ENV: "test"
   COVERAGE: "true"
   MYSQL_HOST: "mysql"
   MYSQL_PASSWORD: "sinclair"
   MYSQL_ROOT_PASSWORD: "sinclair"
   MYSQL_DATABASE: "scraper_test"

before_script:
   - bundle install --jobs 4 --deployment
   - cp config/database.yml.example config/database.yml
   - cp config/secrets.yml.example  config/secrets.yml
   - cp config/settings/example.yml config/settings/test.yml
   - mkdir -p reports/

stages:
   - test

test:
   script:
      - bundle exec rake db:drop db:create db:migrate
      - bundle exec rake app:reports
   tags:
      - docker
   coverage: '/\(\d+.\d+\%\) covered/'
   artifacts:
      paths:
         - reports/
