version: '3.6'
services:
  scraper:
    container_name: scraper_ws
    build: .
    stdin_open: ${DOCKERTTY}
    tty: ${DOCKERTTY}
    volumes:
      - .:/usr/src/app
      - ~/.ssh:/root/.ssh
      - ./public/system:/usr/src/app/public/system
    ports:
      - "3000:3000"
    depends_on:
      - scraper-db
    env_file:
      - '.env'

  scraper-db:
    container_name: scraper_db
    image: mysql:5.7.22
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: sinclair
    volumes:
      - ./db/data:/var/lib/mysql
    env_file:
      - '.env'