version: '3.1'
services:
  scraper:
    container_name: scraper_ws
    stdin_open: ${DOCKERTTY}
    tty: ${DOCKERTTY}
    build: .
    volumes:
      - ./:/usr/src/scraper
      - ~/.ssh:/root/.ssh
    ports:
      - "3000:3000"
    depends_on:
      - scraper-db

  scraper-db:
    container_name: scraper_db
    image: mysql:5.7.22
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: sinclair
    volumes:
      - ./db/data:/var/lib/mysql
