version: '3.6'
services:
  scraper:
    platform: linux/x86_64
    container_name: scraper_ws
    build: .
    stdin_open: ${DOCKERTTY}
    tty: ${DOCKERTTY}
    volumes:
      - ./:/usr/src/scraper
      - ~/.ssh:/root/.ssh
      - ./public/system:/usr/src/app/public/system
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: scraper_db
    image: mysql:8.0.26
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: sinclair
    volumes:
      - ./db/data:/var/lib/mysql